/*
 * generated by Xtext
 */
package de.nittka.tooling.xarchive;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XarchiveRuntimeModule extends de.nittka.tooling.xarchive.AbstractXarchiveRuntimeModule {

}
