/*******************************************************************************
 * Copyright (C) 2016-2020 Alexander Nittka (alex@nittka.de)
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/*
* generated by Xtext
*/
package de.nittka.tooling.xarchive;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XarchiveStandaloneSetup extends XarchiveStandaloneSetupGenerated{

	public static void doSetup() {
		new XarchiveStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

