/*******************************************************************************
 * Copyright (C) 2016-2020 Alexander Nittka (alex@nittka.de)
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/*
 * generated by Xtext
 */
package de.nittka.tooling.xarchive;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import de.nittka.tooling.xarchive.index.XarchiveResourceDescriptionStrategy;
import de.nittka.tooling.xarchive.scoping.XarchiveNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XarchiveRuntimeModule extends de.nittka.tooling.xarchive.AbstractXarchiveRuntimeModule {

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return XarchiveNameProvider.class;
	}

	public Class<? extends IDefaultResourceDescriptionStrategy> bindResourceDescriptionStrategy() {
		return XarchiveResourceDescriptionStrategy.class;
	}

}
