/*
* generated by Xtext
*/
package de.nittka.tooling.xarchive;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XarchiveStandaloneSetup extends XarchiveStandaloneSetupGenerated{

	public static void doSetup() {
		new XarchiveStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

