/*
 * generated by Xtext
 */
package de.nittka.tooling.xarchive.ui.contentassist

import de.nittka.tooling.xarchive.ui.contentassist.AbstractXarchiveProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class XarchiveProposalProvider extends AbstractXarchiveProposalProvider {
}
