/*
 * generated by Xtext
 */
package de.nittka.tooling.xarchive.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XarchiveUiModule extends de.nittka.tooling.xarchive.ui.AbstractXarchiveUiModule {
	public XarchiveUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public com.google.inject.Provider<org.eclipse.xtext.resource.containers.IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

}
